### ISSUE TITLE
404 on Examples link (kinference-examples)

### ISSUE THREAD

**Issue by davidtcdeveloper** [JetBrains-Research/kinference#198]
Hi everyone!

I just found this repo and I am interested on checking some usage samples but the link listed in [README](https://github.com/JetBrains-Research/kinference?tab=readme-ov-file#examples) file seems to be broken.

Either the [kinference-examples](https://github.com/JetBrains-Research/kinference-examples) repo doesn't exist anymore or it's not public.

Could you point me to the proper samples location?

Thanks in advance.

**Comment by dmitriyb** [comment]
We are working on new examples. They will be in this repository starting next week.

**Comment by anthonyolazabal** [comment]
Hi @dmitriyb  I'm also interested in examples on how to use Kinference, do you know when they are going to be live ? Thanks in advance for your answer

**Comment by dmitriyb** [comment]
Hi @anthonyolazabal, we are preparing a new release right now and plan to include examples there. I will write here as soon as we finish

**Comment by anthonyolazabal** [comment]
thanks for your feedback @dmitriyb I will have a look at it once online.

**Comment by dmitriyb** [comment]
@nmssalman I have already finished an example with image classification. Now, I am finishing the gpt-2 example. The expected time is this week: we found a bug with some cases for broadcasting and fixed it. If you want to check the classification example for jvm, it is located [here](https://github.com/JetBrains-Research/kinference/tree/examples/examples/src/jvmMain/kotlin/io/kinference/examples/classification).

**Comment by dmitriyb** [comment]
New examples were added in the [examples](https://github.com/JetBrains-Research/kinference/tree/master/examples) module.
