### ISSUE TITLE
Latest package seems missing (0.10.0)

### ISSUE THREAD

**Issue by Lundez** [JetBrains-Research/kinference#35]
See link to registry: https://packages.jetbrains.team/maven/p/ki/maven/io/kinference/inference/

**Comment by TanVD** [comment]
Please, use inference-core-jvm :)

**Comment by TanVD** [comment]
Will update README

**Comment by Lundez** [comment]
Thanks

**Comment by TanVD** [comment]
BTW, do you want to use KInference for your NLP project? 

We do pretty similar things in JetBrains. If you wish to discuss it, drop me a message at Vladislav.Tankov@jetbrains.com

**Comment by Lundez** [comment]
@TanVD I'll most likely reach out this weekend. 
This exact question was actually related to a image project I'm working on privately (currently using DJL, but thought 

Kinference would be lighter and also I seem to be able to use KotlinJS if I really want to stretch it into the web, rather than server-based.

---

For my NLP toolkit I'm currently investigating possibilities, I think DJL vs KInference are the choices. DJL has a better ecosystem over all as it aims to solve a larger issue than KInference (model-zoo, tokenizations through huggingface/sentencepiece etc)


Thanks for the assistance, closing this issue based on update.
