### ISSUE TITLE
Could not find io.kinference:inference:0.1.12

### ISSUE THREAD

**Issue by antonarhipov** [JetBrains-Research/kinference#38]
If defined the repository and dependency coordinates as stated in the README, I get the following:

Execution failed for task ':compileKotlinJvm'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlinJvm'
   > Could not resolve all files for configuration ':jvmCompileClasspath'.
      > Could not find io.kinference:inference:0.1.12.
        Searched in the following locations:
          - https://packages.jetbrains.team/maven/p/ki/maven/io/kinference/inference/0.1.12/inference-0.1.12.pom
          - https://repo.maven.apache.org/maven2/io/kinference/inference/0.1.12/inference-0.1.12.pom

Should I use inference-api instead? ("io.kinference:inference-api:0.1.12")

**Comment by cupertank** [comment]
The "inference" module is deprecated. If you need a standard KInference JVM use the "kinference-core" module.

**Comment by cupertank** [comment]
I have updated the package name in the README https://github.com/JetBrains-Research/kinference/commit/de50087b8dba2b2aafdd7615e8bceebb4edeef6c
